name: fetch_url
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  go_router: ^8.0.3
  google_fonts: ^5.0.0
  url_launcher: ^6.1.11
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  rive: ^0.7.16
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  build_runner: ^2.4.5
  riverpod_generator: ^2.2.3
  go_router_builder: ^2.1.1
  build_verify: ^3.1.0
  isar_generator: ^3.1.0+1
  freezed: ^2.3.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/animation/
